version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user-keycloak
      POSTGRES_PASSWORD: password-keycloak
      POSTGRES_DB: db-keycloak
    volumes: 
      - "./datadir:/var/lib/postgresql/data"

  keycloak:
      image: quay.io/keycloak/keycloak:13.0.1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: db-keycloak
        DB_USER: user-keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password-keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 28080:8080
      depends_on:
        - postgres
