---
# defaults file for openliberty
openliberty_release: "2021-03-09_1101"
openliberty_version: "21.0.0.3"
openliberty_checksum: "sha512:e6f587ab53b79f0b99cc2a758bb8910198eaa0721fa79a168bf2e415c841a7e691e005220a15ee04332eb1de8390491a0d82f5355f089ab7d3caddc13704167f"
jee_runtimes_home: "{{ ansible_env.HOME }}/jee-runtimes"
openliberty_home: "{{ jee_runtimes_home }}/openliberty"
