---
# defaults file for openliberty
openliberty_release: "2021-05-10_1231"
openliberty_version: "21.0.0.5"
openliberty_checksum: "sha512:1cae98d31af061d92303f0ef2e0dccf89878e1dd3ed6da0bf7e5a29054773e65db7d7898f238e34574e36a4490696ccf68643f95430b13b8e8a614aa88b3aa39"
jee_runtimes_home: "{{ ansible_env.HOME }}/jee-runtimes"
openliberty_home: "{{ jee_runtimes_home }}/openliberty"
